name: Npm Package Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm i
      - run: npm run build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
          npm login --scope=@<scope> --registry=https://registry.npmjs.org/
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=format:"%ae")
          git config --global user.name $COMMIT_AUTHOR
          git config --global user.email $COMMIT_AUTHOR_EMAIL
          npm version patch
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
